const URL = "https://api.github.com/search/users?q=";


const jsonResponse = '''{
  "total_count": 27920,
  "incomplete_results": false,
  "items": [
    {
      "login": "jacob",
      "id": 3121,
      "node_id": "MDQ6VXNlcjMxMjE=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/3121?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacob",
      "html_url": "https://github.com/jacob",
      "followers_url": "https://api.github.com/users/jacob/followers",
      "following_url": "https://api.github.com/users/jacob/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacob/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacob/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacob/subscriptions",
      "organizations_url": "https://api.github.com/users/jacob/orgs",
      "repos_url": "https://api.github.com/users/jacob/repos",
      "events_url": "https://api.github.com/users/jacob/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacob/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}''';

const githubResult = """
{
  "total_count": 73,
  "incomplete_results": false,
  "items": [
    {
      "login": "Rychard",
      "id": 2145848,
      "node_id": "MDQ6VXNlcjIxNDU4NDg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2145848?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Rychard",
      "html_url": "https://github.com/Rychard",
      "followers_url": "https://api.github.com/users/Rychard/followers",
      "following_url": "https://api.github.com/users/Rychard/following{/other_user}",
      "gists_url": "https://api.github.com/users/Rychard/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Rychard/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Rychard/subscriptions",
      "organizations_url": "https://api.github.com/users/Rychard/orgs",
      "repos_url": "https://api.github.com/users/Rychard/repos",
      "events_url": "https://api.github.com/users/Rychard/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Rychard/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "RychardHunt",
      "id": 22261791,
      "node_id": "MDQ6VXNlcjIyMjYxNzkx",
      "avatar_url": "https://avatars.githubusercontent.com/u/22261791?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RychardHunt",
      "html_url": "https://github.com/RychardHunt",
      "followers_url": "https://api.github.com/users/RychardHunt/followers",
      "following_url": "https://api.github.com/users/RychardHunt/following{/other_user}",
      "gists_url": "https://api.github.com/users/RychardHunt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RychardHunt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RychardHunt/subscriptions",
      "organizations_url": "https://api.github.com/users/RychardHunt/orgs",
      "repos_url": "https://api.github.com/users/RychardHunt/repos",
      "events_url": "https://api.github.com/users/RychardHunt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RychardHunt/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychardguedes",
      "id": 9204972,
      "node_id": "MDQ6VXNlcjkyMDQ5NzI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9204972?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychardguedes",
      "html_url": "https://github.com/rychardguedes",
      "followers_url": "https://api.github.com/users/rychardguedes/followers",
      "following_url": "https://api.github.com/users/rychardguedes/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychardguedes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychardguedes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychardguedes/subscriptions",
      "organizations_url": "https://api.github.com/users/rychardguedes/orgs",
      "repos_url": "https://api.github.com/users/rychardguedes/repos",
      "events_url": "https://api.github.com/users/rychardguedes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychardguedes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychard43",
      "id": 44622549,
      "node_id": "MDQ6VXNlcjQ0NjIyNTQ5",
      "avatar_url": "https://avatars.githubusercontent.com/u/44622549?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychard43",
      "html_url": "https://github.com/rychard43",
      "followers_url": "https://api.github.com/users/rychard43/followers",
      "following_url": "https://api.github.com/users/rychard43/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychard43/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychard43/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychard43/subscriptions",
      "organizations_url": "https://api.github.com/users/rychard43/orgs",
      "repos_url": "https://api.github.com/users/rychard43/repos",
      "events_url": "https://api.github.com/users/rychard43/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychard43/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "RychardCosta",
      "id": 55329339,
      "node_id": "MDQ6VXNlcjU1MzI5MzM5",
      "avatar_url": "https://avatars.githubusercontent.com/u/55329339?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RychardCosta",
      "html_url": "https://github.com/RychardCosta",
      "followers_url": "https://api.github.com/users/RychardCosta/followers",
      "following_url": "https://api.github.com/users/RychardCosta/following{/other_user}",
      "gists_url": "https://api.github.com/users/RychardCosta/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RychardCosta/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RychardCosta/subscriptions",
      "organizations_url": "https://api.github.com/users/RychardCosta/orgs",
      "repos_url": "https://api.github.com/users/RychardCosta/repos",
      "events_url": "https://api.github.com/users/RychardCosta/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RychardCosta/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "RychardGutierrez",
      "id": 59939891,
      "node_id": "MDQ6VXNlcjU5OTM5ODkx",
      "avatar_url": "https://avatars.githubusercontent.com/u/59939891?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RychardGutierrez",
      "html_url": "https://github.com/RychardGutierrez",
      "followers_url": "https://api.github.com/users/RychardGutierrez/followers",
      "following_url": "https://api.github.com/users/RychardGutierrez/following{/other_user}",
      "gists_url": "https://api.github.com/users/RychardGutierrez/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RychardGutierrez/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RychardGutierrez/subscriptions",
      "organizations_url": "https://api.github.com/users/RychardGutierrez/orgs",
      "repos_url": "https://api.github.com/users/RychardGutierrez/repos",
      "events_url": "https://api.github.com/users/RychardGutierrez/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RychardGutierrez/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "RyTeBr",
      "id": 54678174,
      "node_id": "MDQ6VXNlcjU0Njc4MTc0",
      "avatar_url": "https://avatars.githubusercontent.com/u/54678174?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RyTeBr",
      "html_url": "https://github.com/RyTeBr",
      "followers_url": "https://api.github.com/users/RyTeBr/followers",
      "following_url": "https://api.github.com/users/RyTeBr/following{/other_user}",
      "gists_url": "https://api.github.com/users/RyTeBr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RyTeBr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RyTeBr/subscriptions",
      "organizations_url": "https://api.github.com/users/RyTeBr/orgs",
      "repos_url": "https://api.github.com/users/RyTeBr/repos",
      "events_url": "https://api.github.com/users/RyTeBr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RyTeBr/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Rychardsom",
      "id": 25932370,
      "node_id": "MDQ6VXNlcjI1OTMyMzcw",
      "avatar_url": "https://avatars.githubusercontent.com/u/25932370?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Rychardsom",
      "html_url": "https://github.com/Rychardsom",
      "followers_url": "https://api.github.com/users/Rychardsom/followers",
      "following_url": "https://api.github.com/users/Rychardsom/following{/other_user}",
      "gists_url": "https://api.github.com/users/Rychardsom/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Rychardsom/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Rychardsom/subscriptions",
      "organizations_url": "https://api.github.com/users/Rychardsom/orgs",
      "repos_url": "https://api.github.com/users/Rychardsom/repos",
      "events_url": "https://api.github.com/users/Rychardsom/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Rychardsom/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychardhiago",
      "id": 49962256,
      "node_id": "MDQ6VXNlcjQ5OTYyMjU2",
      "avatar_url": "https://avatars.githubusercontent.com/u/49962256?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychardhiago",
      "html_url": "https://github.com/rychardhiago",
      "followers_url": "https://api.github.com/users/rychardhiago/followers",
      "following_url": "https://api.github.com/users/rychardhiago/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychardhiago/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychardhiago/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychardhiago/subscriptions",
      "organizations_url": "https://api.github.com/users/rychardhiago/orgs",
      "repos_url": "https://api.github.com/users/rychardhiago/repos",
      "events_url": "https://api.github.com/users/rychardhiago/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychardhiago/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychardemanne",
      "id": 30099415,
      "node_id": "MDQ6VXNlcjMwMDk5NDE1",
      "avatar_url": "https://avatars.githubusercontent.com/u/30099415?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychardemanne",
      "html_url": "https://github.com/rychardemanne",
      "followers_url": "https://api.github.com/users/rychardemanne/followers",
      "following_url": "https://api.github.com/users/rychardemanne/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychardemanne/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychardemanne/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychardemanne/subscriptions",
      "organizations_url": "https://api.github.com/users/rychardemanne/orgs",
      "repos_url": "https://api.github.com/users/rychardemanne/repos",
      "events_url": "https://api.github.com/users/rychardemanne/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychardemanne/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "VeRychard",
      "id": 10435459,
      "node_id": "MDQ6VXNlcjEwNDM1NDU5",
      "avatar_url": "https://avatars.githubusercontent.com/u/10435459?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/VeRychard",
      "html_url": "https://github.com/VeRychard",
      "followers_url": "https://api.github.com/users/VeRychard/followers",
      "following_url": "https://api.github.com/users/VeRychard/following{/other_user}",
      "gists_url": "https://api.github.com/users/VeRychard/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/VeRychard/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/VeRychard/subscriptions",
      "organizations_url": "https://api.github.com/users/VeRychard/orgs",
      "repos_url": "https://api.github.com/users/VeRychard/repos",
      "events_url": "https://api.github.com/users/VeRychard/events{/privacy}",
      "received_events_url": "https://api.github.com/users/VeRychard/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "RychardMenezes",
      "id": 56650719,
      "node_id": "MDQ6VXNlcjU2NjUwNzE5",
      "avatar_url": "https://avatars.githubusercontent.com/u/56650719?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RychardMenezes",
      "html_url": "https://github.com/RychardMenezes",
      "followers_url": "https://api.github.com/users/RychardMenezes/followers",
      "following_url": "https://api.github.com/users/RychardMenezes/following{/other_user}",
      "gists_url": "https://api.github.com/users/RychardMenezes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RychardMenezes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RychardMenezes/subscriptions",
      "organizations_url": "https://api.github.com/users/RychardMenezes/orgs",
      "repos_url": "https://api.github.com/users/RychardMenezes/repos",
      "events_url": "https://api.github.com/users/RychardMenezes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RychardMenezes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychardvale",
      "id": 54805553,
      "node_id": "MDQ6VXNlcjU0ODA1NTUz",
      "avatar_url": "https://avatars.githubusercontent.com/u/54805553?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychardvale",
      "html_url": "https://github.com/rychardvale",
      "followers_url": "https://api.github.com/users/rychardvale/followers",
      "following_url": "https://api.github.com/users/rychardvale/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychardvale/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychardvale/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychardvale/subscriptions",
      "organizations_url": "https://api.github.com/users/rychardvale/orgs",
      "repos_url": "https://api.github.com/users/rychardvale/repos",
      "events_url": "https://api.github.com/users/rychardvale/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychardvale/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychardcdm",
      "id": 57567153,
      "node_id": "MDQ6VXNlcjU3NTY3MTUz",
      "avatar_url": "https://avatars.githubusercontent.com/u/57567153?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychardcdm",
      "html_url": "https://github.com/rychardcdm",
      "followers_url": "https://api.github.com/users/rychardcdm/followers",
      "following_url": "https://api.github.com/users/rychardcdm/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychardcdm/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychardcdm/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychardcdm/subscriptions",
      "organizations_url": "https://api.github.com/users/rychardcdm/orgs",
      "repos_url": "https://api.github.com/users/rychardcdm/repos",
      "events_url": "https://api.github.com/users/rychardcdm/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychardcdm/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychardwik",
      "id": 29128443,
      "node_id": "MDQ6VXNlcjI5MTI4NDQz",
      "avatar_url": "https://avatars.githubusercontent.com/u/29128443?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychardwik",
      "html_url": "https://github.com/rychardwik",
      "followers_url": "https://api.github.com/users/rychardwik/followers",
      "following_url": "https://api.github.com/users/rychardwik/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychardwik/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychardwik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychardwik/subscriptions",
      "organizations_url": "https://api.github.com/users/rychardwik/orgs",
      "repos_url": "https://api.github.com/users/rychardwik/repos",
      "events_url": "https://api.github.com/users/rychardwik/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychardwik/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychardgoltara",
      "id": 40506078,
      "node_id": "MDQ6VXNlcjQwNTA2MDc4",
      "avatar_url": "https://avatars.githubusercontent.com/u/40506078?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychardgoltara",
      "html_url": "https://github.com/rychardgoltara",
      "followers_url": "https://api.github.com/users/rychardgoltara/followers",
      "following_url": "https://api.github.com/users/rychardgoltara/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychardgoltara/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychardgoltara/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychardgoltara/subscriptions",
      "organizations_url": "https://api.github.com/users/rychardgoltara/orgs",
      "repos_url": "https://api.github.com/users/rychardgoltara/repos",
      "events_url": "https://api.github.com/users/rychardgoltara/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychardgoltara/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychardcs15",
      "id": 49370488,
      "node_id": "MDQ6VXNlcjQ5MzcwNDg4",
      "avatar_url": "https://avatars.githubusercontent.com/u/49370488?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychardcs15",
      "html_url": "https://github.com/rychardcs15",
      "followers_url": "https://api.github.com/users/rychardcs15/followers",
      "following_url": "https://api.github.com/users/rychardcs15/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychardcs15/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychardcs15/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychardcs15/subscriptions",
      "organizations_url": "https://api.github.com/users/rychardcs15/orgs",
      "repos_url": "https://api.github.com/users/rychardcs15/repos",
      "events_url": "https://api.github.com/users/rychardcs15/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychardcs15/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "RychardM",
      "id": 22275248,
      "node_id": "MDQ6VXNlcjIyMjc1MjQ4",
      "avatar_url": "https://avatars.githubusercontent.com/u/22275248?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RychardM",
      "html_url": "https://github.com/RychardM",
      "followers_url": "https://api.github.com/users/RychardM/followers",
      "following_url": "https://api.github.com/users/RychardM/following{/other_user}",
      "gists_url": "https://api.github.com/users/RychardM/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RychardM/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RychardM/subscriptions",
      "organizations_url": "https://api.github.com/users/RychardM/orgs",
      "repos_url": "https://api.github.com/users/RychardM/repos",
      "events_url": "https://api.github.com/users/RychardM/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RychardM/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Rychard91",
      "id": 57370717,
      "node_id": "MDQ6VXNlcjU3MzcwNzE3",
      "avatar_url": "https://avatars.githubusercontent.com/u/57370717?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Rychard91",
      "html_url": "https://github.com/Rychard91",
      "followers_url": "https://api.github.com/users/Rychard91/followers",
      "following_url": "https://api.github.com/users/Rychard91/following{/other_user}",
      "gists_url": "https://api.github.com/users/Rychard91/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Rychard91/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Rychard91/subscriptions",
      "organizations_url": "https://api.github.com/users/Rychard91/orgs",
      "repos_url": "https://api.github.com/users/Rychard91/repos",
      "events_url": "https://api.github.com/users/Rychard91/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Rychard91/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Rychardsscott",
      "id": 28066386,
      "node_id": "MDQ6VXNlcjI4MDY2Mzg2",
      "avatar_url": "https://avatars.githubusercontent.com/u/28066386?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Rychardsscott",
      "html_url": "https://github.com/Rychardsscott",
      "followers_url": "https://api.github.com/users/Rychardsscott/followers",
      "following_url": "https://api.github.com/users/Rychardsscott/following{/other_user}",
      "gists_url": "https://api.github.com/users/Rychardsscott/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Rychardsscott/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Rychardsscott/subscriptions",
      "organizations_url": "https://api.github.com/users/Rychardsscott/orgs",
      "repos_url": "https://api.github.com/users/Rychardsscott/repos",
      "events_url": "https://api.github.com/users/Rychardsscott/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Rychardsscott/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychard-pitoy",
      "id": 57356057,
      "node_id": "MDQ6VXNlcjU3MzU2MDU3",
      "avatar_url": "https://avatars.githubusercontent.com/u/57356057?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychard-pitoy",
      "html_url": "https://github.com/rychard-pitoy",
      "followers_url": "https://api.github.com/users/rychard-pitoy/followers",
      "following_url": "https://api.github.com/users/rychard-pitoy/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychard-pitoy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychard-pitoy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychard-pitoy/subscriptions",
      "organizations_url": "https://api.github.com/users/rychard-pitoy/orgs",
      "repos_url": "https://api.github.com/users/rychard-pitoy/repos",
      "events_url": "https://api.github.com/users/rychard-pitoy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychard-pitoy/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychard2712",
      "id": 52903042,
      "node_id": "MDQ6VXNlcjUyOTAzMDQy",
      "avatar_url": "https://avatars.githubusercontent.com/u/52903042?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychard2712",
      "html_url": "https://github.com/rychard2712",
      "followers_url": "https://api.github.com/users/rychard2712/followers",
      "following_url": "https://api.github.com/users/rychard2712/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychard2712/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychard2712/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychard2712/subscriptions",
      "organizations_url": "https://api.github.com/users/rychard2712/orgs",
      "repos_url": "https://api.github.com/users/rychard2712/repos",
      "events_url": "https://api.github.com/users/rychard2712/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychard2712/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Rycharde",
      "id": 12788040,
      "node_id": "MDQ6VXNlcjEyNzg4MDQw",
      "avatar_url": "https://avatars.githubusercontent.com/u/12788040?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Rycharde",
      "html_url": "https://github.com/Rycharde",
      "followers_url": "https://api.github.com/users/Rycharde/followers",
      "following_url": "https://api.github.com/users/Rycharde/following{/other_user}",
      "gists_url": "https://api.github.com/users/Rycharde/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Rycharde/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Rycharde/subscriptions",
      "organizations_url": "https://api.github.com/users/Rycharde/orgs",
      "repos_url": "https://api.github.com/users/Rycharde/repos",
      "events_url": "https://api.github.com/users/Rycharde/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Rycharde/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychard3",
      "id": 51341949,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjUxMzQxOTQ5",
      "avatar_url": "https://avatars.githubusercontent.com/u/51341949?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychard3",
      "html_url": "https://github.com/rychard3",
      "followers_url": "https://api.github.com/users/rychard3/followers",
      "following_url": "https://api.github.com/users/rychard3/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychard3/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychard3/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychard3/subscriptions",
      "organizations_url": "https://api.github.com/users/rychard3/orgs",
      "repos_url": "https://api.github.com/users/rychard3/repos",
      "events_url": "https://api.github.com/users/rychard3/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychard3/received_events",
      "type": "Organization",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychardeh",
      "id": 18443509,
      "node_id": "MDQ6VXNlcjE4NDQzNTA5",
      "avatar_url": "https://avatars.githubusercontent.com/u/18443509?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychardeh",
      "html_url": "https://github.com/rychardeh",
      "followers_url": "https://api.github.com/users/rychardeh/followers",
      "following_url": "https://api.github.com/users/rychardeh/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychardeh/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychardeh/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychardeh/subscriptions",
      "organizations_url": "https://api.github.com/users/rychardeh/orgs",
      "repos_url": "https://api.github.com/users/rychardeh/repos",
      "events_url": "https://api.github.com/users/rychardeh/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychardeh/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "RychardAndrey",
      "id": 29320560,
      "node_id": "MDQ6VXNlcjI5MzIwNTYw",
      "avatar_url": "https://avatars.githubusercontent.com/u/29320560?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RychardAndrey",
      "html_url": "https://github.com/RychardAndrey",
      "followers_url": "https://api.github.com/users/RychardAndrey/followers",
      "following_url": "https://api.github.com/users/RychardAndrey/following{/other_user}",
      "gists_url": "https://api.github.com/users/RychardAndrey/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RychardAndrey/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RychardAndrey/subscriptions",
      "organizations_url": "https://api.github.com/users/RychardAndrey/orgs",
      "repos_url": "https://api.github.com/users/RychardAndrey/repos",
      "events_url": "https://api.github.com/users/RychardAndrey/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RychardAndrey/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychardpitoy",
      "id": 55572947,
      "node_id": "MDQ6VXNlcjU1NTcyOTQ3",
      "avatar_url": "https://avatars.githubusercontent.com/u/55572947?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychardpitoy",
      "html_url": "https://github.com/rychardpitoy",
      "followers_url": "https://api.github.com/users/rychardpitoy/followers",
      "following_url": "https://api.github.com/users/rychardpitoy/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychardpitoy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychardpitoy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychardpitoy/subscriptions",
      "organizations_url": "https://api.github.com/users/rychardpitoy/orgs",
      "repos_url": "https://api.github.com/users/rychardpitoy/repos",
      "events_url": "https://api.github.com/users/rychardpitoy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychardpitoy/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychardruan13",
      "id": 60975377,
      "node_id": "MDQ6VXNlcjYwOTc1Mzc3",
      "avatar_url": "https://avatars.githubusercontent.com/u/60975377?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychardruan13",
      "html_url": "https://github.com/rychardruan13",
      "followers_url": "https://api.github.com/users/rychardruan13/followers",
      "following_url": "https://api.github.com/users/rychardruan13/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychardruan13/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychardruan13/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychardruan13/subscriptions",
      "organizations_url": "https://api.github.com/users/rychardruan13/orgs",
      "repos_url": "https://api.github.com/users/rychardruan13/repos",
      "events_url": "https://api.github.com/users/rychardruan13/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychardruan13/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rychard99",
      "id": 53287356,
      "node_id": "MDQ6VXNlcjUzMjg3MzU2",
      "avatar_url": "https://avatars.githubusercontent.com/u/53287356?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rychard99",
      "html_url": "https://github.com/rychard99",
      "followers_url": "https://api.github.com/users/rychard99/followers",
      "following_url": "https://api.github.com/users/rychard99/following{/other_user}",
      "gists_url": "https://api.github.com/users/rychard99/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rychard99/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rychard99/subscriptions",
      "organizations_url": "https://api.github.com/users/rychard99/orgs",
      "repos_url": "https://api.github.com/users/rychard99/repos",
      "events_url": "https://api.github.com/users/rychard99/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rychard99/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Rychard1986",
      "id": 33291230,
      "node_id": "MDQ6VXNlcjMzMjkxMjMw",
      "avatar_url": "https://avatars.githubusercontent.com/u/33291230?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Rychard1986",
      "html_url": "https://github.com/Rychard1986",
      "followers_url": "https://api.github.com/users/Rychard1986/followers",
      "following_url": "https://api.github.com/users/Rychard1986/following{/other_user}",
      "gists_url": "https://api.github.com/users/Rychard1986/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Rychard1986/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Rychard1986/subscriptions",
      "organizations_url": "https://api.github.com/users/Rychard1986/orgs",
      "repos_url": "https://api.github.com/users/Rychard1986/repos",
      "events_url": "https://api.github.com/users/Rychard1986/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Rychard1986/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
 """;